# Site settings
title: Things At Home
email: schubert.konstantin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Things have in our home. Things we like. Because of their high quality, 
  the beaufiful design, their sturdiness or because the price is really good.
  This is a blog about things we would recommend to our friends. 
baseurl: "" # the subpath of your site, e.g. /blog/
# twitter_username: jekyllrb
# github_username:  schubert.konstantin@gmail.com

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
